phrase:
  project_id: 9a79f9493ac786469bd1154c8e25e68d
  file_format: yml 
  
  push:
    sources:
    - file: zh.yml
      params:
        locale_id: zh
        update_translations: true
        update_descriptions: false
  pull:
    targets:
    - file: zh.yml
      params:
        file_format: yml
        locale_id: zh
        include_empty_translations: false 
        exclude_empty_zero_forms: false 
        include_translated_keys: true 
        keep_notranslate_tags: false 
        encoding: UTF-8 
        include_unverified_translations: true 
        use_last_reviewed_version: false 
        fallback_locale_id: ch
        #-------------
        format_options:
          enclose_in_cdata: false
          include_translation_state: false
          indent_size: 4
          indent_style: space
          delimit_placeholders: false
          convert_placeholder: false
          include_pluralized_keys: false
          export_tags: false
          export_max_characters_allowed: false
          escape_linebreaks: false
          escape_single_quotes: false
          omit_separator_space: false
          crlf_line_terminators: false
