phrase:
  project_id: 9a79f9493ac786469bd1154c8e25e68d
  file_format: yml 
  
  push:
    sources:
    - file: zh.yml
      params:
        file_format: yml
        locale_id: zh
        update_translations: true
        update_descriptions: false
        file_encoding: "UTF-8" 
        skip_upload_tags: false
        autotranslate: false
        mark_reviewed: false
  pull:
    targets:
    - file: zh.yml
      params:
        file_format: yml
        locale_id: zh
        include_empty_translations: false 
        exclude_empty_zero_forms: false 
        include_translated_keys: true 
        keep_notranslate_tags: false 
        file_encoding: "UTF-8"
        include_unverified_translations: true 
        use_last_reviewed_version: false 
        fallback_locale_id: zh
